replicaCount: 1

image:
  repository: https://registry-1.docker.io/avivbe594/dummy:consumer1
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5001

livenessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 10

resources: {}
