apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/helm-charts.git'
    targetRevision: HEAD
    chart: 'consumer-chart'
    helm:
      valueFiles:
        - values/consumer-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
