apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/avivbenezra/dummyservice
    targetRevision: consumer-chart
    chart: consumer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
