apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://registry-1.docker.io/bitnamicharts/kafka
    targetRevision: latest
    helm:
      valueFiles:
        - values/kafka-values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
