apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/
    chart: bitnamicharts/mongodb
    targetRevision: 15.6.0
    helm:
      valueFiles:
        - values/mongodb-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
