replicaSet:
  enabled: true

persistence:
  enabled: true

architecture: replicaset

auth:
  enabled: true
  rootPassword: basketball
  username: admin
  password: pass
  database: mydatabase

service:
  type: ClusterIP
  port: 27017

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
