replicaCount: 2

persistence:
  enabled: true

zookeeper:
  enabled: true

service:
  type: ClusterIP
  port: 9092

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
